with open("/tmp/crack_999.c", "w") as f:
    f.write('#include <stdio.h>\n')
    f.write('#include <string.h>\n')
    f.write('#include <openssl/md5.h>\n')
    f.write('const char *t = "79dca16741891333";\n')
    f.write('int ck(const char *p) {\n')
    f.write('  unsigned char h[16]; char x[33];\n')
    f.write('  MD5((unsigned char*)p, strlen(p), h);\n')
    f.write('  for (int i=0;i<16;i++) sprintf(x+i*2,"%02x",h[i]);\n')
    f.write('  x[32]=0; return strncmp(x+8,t,16)==0;\n')
    f.write('}\n')
    f.write('int main() {\n')
    f.write('  char p[10]; long c=0;\n')
    f.write('  for (int a=97;a<123;a++)\n')
    f.write('  for (int b=97;b<123;b++)\n')
    f.write('  for (int c2=97;c2<123;c2++)\n')
    f.write('  for (int d=97;d<123;d++)\n')
    f.write('  for (int e=97;e<123;e++)\n')
    f.write('  for (int f=97;f<123;f++) {\n')
    f.write('    p[0]=a;p[1]=b;p[2]=c2;p[3]=d;p[4]=e;p[5]=f;p[6]=0;\n')
    f.write('    if(ck(p)){printf("FOUND: %s\\n",p);return 0;}\n')
    f.write('    c++;if(c%5000000==0)fprintf(stderr,"p: %ld\\n",c);\n')
    f.write('  }\n')
    f.write('  printf("Done: %ld\\n",c); return 1;\n')
    f.write('}\n')
print("Written")
